namespace DevToolbox.Tools.MimeTypes
{
    /// <summary>
    /// Static reference data for the "List of MIME Types" tool: common file extensions mapped to
    /// their standard MIME type string. Limited to well-known, widely-documented mappings rather
    /// than an exhaustive (and error-prone) list of every registered media type.
    /// </summary>
    public static class MimeTypeData
    {
        public static readonly string[][] Rows =
        {
            new[] { ".html", "text/html" },
            new[] { ".htm", "text/html" },
            new[] { ".css", "text/css" },
            new[] { ".js", "text/javascript" },
            new[] { ".mjs", "text/javascript" },
            new[] { ".json", "application/json" },
            new[] { ".xml", "application/xml" },
            new[] { ".csv", "text/csv" },
            new[] { ".txt", "text/plain" },
            new[] { ".md", "text/markdown" },
            new[] { ".pdf", "application/pdf" },
            new[] { ".doc", "application/msword" },
            new[] { ".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
            new[] { ".xls", "application/vnd.ms-excel" },
            new[] { ".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
            new[] { ".ppt", "application/vnd.ms-powerpoint" },
            new[] { ".pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
            new[] { ".png", "image/png" },
            new[] { ".jpg", "image/jpeg" },
            new[] { ".jpeg", "image/jpeg" },
            new[] { ".gif", "image/gif" },
            new[] { ".svg", "image/svg+xml" },
            new[] { ".webp", "image/webp" },
            new[] { ".ico", "image/vnd.microsoft.icon" },
            new[] { ".bmp", "image/bmp" },
            new[] { ".tiff", "image/tiff" },
            new[] { ".mp3", "audio/mpeg" },
            new[] { ".wav", "audio/wav" },
            new[] { ".ogg", "audio/ogg" },
            new[] { ".mp4", "video/mp4" },
            new[] { ".webm", "video/webm" },
            new[] { ".avi", "video/x-msvideo" },
            new[] { ".mov", "video/quicktime" },
            new[] { ".mkv", "video/x-matroska" },
            new[] { ".zip", "application/zip" },
            new[] { ".gz", "application/gzip" },
            new[] { ".tar", "application/x-tar" },
            new[] { ".rar", "application/vnd.rar" },
            new[] { ".7z", "application/x-7z-compressed" },
            new[] { ".ttf", "font/ttf" },
            new[] { ".otf", "font/otf" },
            new[] { ".woff", "font/woff" },
            new[] { ".woff2", "font/woff2" },
            new[] { ".eot", "application/vnd.ms-fontobject" },
            new[] { ".wasm", "application/wasm" },
            new[] { ".exe", "application/vnd.microsoft.portable-executable" },
            new[] { ".dll", "application/vnd.microsoft.portable-executable" },
            new[] { ".sh", "application/x-sh" },
            new[] { ".bat", "application/x-bat" },
            new[] { ".ps1", "application/octet-stream" },
            new[] { ".py", "text/x-python" },
            new[] { ".java", "text/x-java-source" },
            new[] { ".c", "text/x-csrc" },
            new[] { ".cpp", "text/x-c++src" },
            new[] { ".h", "text/x-chdr" },
            new[] { ".cs", "text/plain" },
            new[] { ".php", "application/x-httpd-php" },
            new[] { ".rb", "text/x-ruby" },
            new[] { ".go", "text/x-go" },
            new[] { ".rs", "text/rust" },
            new[] { ".sql", "application/sql" },
            new[] { ".yaml", "application/x-yaml" },
            new[] { ".yml", "application/x-yaml" },
            new[] { ".ini", "text/plain" },
            new[] { ".log", "text/plain" },
            new[] { ".apk", "application/vnd.android.package-archive" },
            new[] { ".jar", "application/java-archive" },
            new[] { ".epub", "application/epub+zip" },
            new[] { ".rtf", "application/rtf" },
            new[] { ".swf", "application/x-shockwave-flash" },
        };
    }
}
